trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  awsRegion: 'eu-west-1'                                   # AWS region for ECR and EC2 instance
  ecrRegistry: '127214202414.dkr.ecr.eu-west-1.amazonaws.com' # ECR registry URI with account ID and region
  repositoryName: 'ca-1'                                # ECR repository name
  imageTag: '$(Build.BuildId)'                             # Tag for the Docker image

steps:
  # Step 1: Install AWS CLI
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
  - script: |
      python -m pip install --upgrade pip
      pip install awscli --upgrade --user
    displayName: 'Install AWS CLI'

  # Step 2: Authenticate Docker with Amazon ECR
  - script: |
      aws ecr get-login-password --region $(awsRegion) | docker login --username AWS --password-stdin $(ecrRegistry)
    displayName: 'Login to Amazon ECR'

  # Step 3: Build Docker Image
  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: 'build'
      dockerfile: '**/Dockerfile'                      # Path to Dockerfile
      tags: '$(ecrRegistry)/$(repositoryName):$(imageTag)'

  # Step 4: Push Docker Image to Amazon ECR
  - task: Docker@2
    displayName: 'Push Docker Image to Amazon ECR'
    inputs:
      command: 'push'
      tags: '$(ecrRegistry)/$(repositoryName):$(imageTag)'

  # Step 5: SSH into EC2 instance and Deploy the Docker Container
  - task: SSH@0
    displayName: 'Deploy Docker Container on EC2'
    inputs:
      sshEndpoint: 'my-ec2-ssh'                        # Azure DevOps service connection for EC2 SSH
      runOptions: 'commands'
      command: |
        docker pull $(ecrRegistry)/$(repositoryName):$(imageTag)
        docker stop sample_app || true                 # Stop existing container
        docker rm sample_app || true                   # Remove existing container
        docker run -d -p 80:80 --name sample_app $(ecrRegistry)/$(repositoryName):$(imageTag)
